# Recording parameters
videoFolder: "/Users/lucas/code/campy/test"
videoFilename: "0.mp4"
frameRate: 10
recTimeInSec: 14400 # total recording time, across all files.

# Trial-based recording
trialStructure: True
trialITI: 1000

# Camera parameters
cameraMake: "flir"
numCams: 2
cameraSelection: [0, 1]
cameraSettings: ""
cameraNames: ['Camera1', 'Camera2']

# Compression parameters
ffmpegLogLevel: ["quiet", "quiet"]
gpuID: -1
pixelFormatInput: "rgb24" # 'bayer_bggr8' 'rgb24'
pixelFormatOutput: "rgb0"
codec: "h264"
quality: "19"

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2

# Other parameters
ffmpegPath: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
frameWidth: [720, 720]
frameHeight: [480, 480]